(* ::Package:: *)

BeginPackage["cmats`"]

Get[FileNameJoin[{DirectoryName[$InputFileName], "utils.m"}]];

stds::usage = "stds[gb, vars] computes the standard, or irreducible, monomials of a Groebner basis `gb` in variables `vars`.";
cmat::usage = "cmat[gb, vars][fun] returns the companion-matrix representation of multiplication by `fun` in the quotient defined by the Groebner basis `gb`.";
cmats::usage = "cmats[poly] returns the multiplication matrices generated by powers of `z` modulo the univariate polynomial `poly`.";
cmatdz::usage = "cmatdz[poly] returns the matrix representation of differentiation with respect to `z` in the `j` basis associated with `poly`.";
dmat::usage = "dmat[form, mat] represents a matrix-valued differential form. It distributes over sums and scalar multiples and composes under `Wedge`.";

Begin["`Private`"]

(* Standard monomials for a Groebner-basis quotient. *)
ClearAll[stds];
Options[stds] = {
    "MonomialOrder" -> DegreeLexicographic,
    Nothing
};

(*
 * Adapted from `CanonicalAndDualBases` in `MultivariateResidue.m`
 * (GPL-3.0):
 * https://bitbucket.org/kjlarsen/multivariateresidues/
 * https://arxiv.org/abs/1701.01040
 *)
stds[gb_List, vars_List, opts:OptionsPattern[]] := stds[gb, vars, opts] = Module[
    {leadingexps, maxexp, basis},
    leadingexps = MonomialList[gb, vars, OptionValue["MonomialOrder"]][[All, 1]] // Map[Exponent[#, vars]&];
    maxexp = leadingexps // Flatten // Max;
    basis = leadingexps // RightComposition[
        Map[Function[exp,
            Select[
                Tuples[Range[0, maxexp], {Length[vars]}],
                Thread[Less[#, exp]]& /* Apply[Or]
            ]
        ]],
        Apply[Intersection],
        Map[vars^#& /* Apply[Times]],
        Total,
        MonomialList[#, vars, OptionValue["MonomialOrder"]]&,
        Reverse,
        Identity
    ]
];
stds[args__] := utils`Error[utils`MkString["Wrong arguments: ", {args} // InputForm]];


(* Companion-matrix representation in a Groebner-basis quotient. *)
ClearAll[cmat];
cmat[gb_List, vars_List][fun_] := stds[gb, vars] // RightComposition[
    Map[fun],
    Map[PolynomialReduce[#, gb, vars]&],
    Part[#, All, 2]&,
    utils`subjs[vars],
    CoefficientArrays[#, stds[gb, vars] // utils`subjs[vars]]&,
    Switch[Length[#],
        2, Last[#],
        1, SparseArray[{}, {Length[Last[#]], Length[Last[#]]}],
        _, utils`Error["wrong dimension in cmat"]
    ]&,
    Transpose,
    Identity
];
cmat[args__][_] := utils`Error[utils`MkString["Wrong arguments: ", {args} // InputForm]];


(* Helpers for the univariate `j` basis used in FiniteFlow work. *)
ClearAll[stdjs, cycles, cmats, cmatdz];
stdjs[poly_] := stdjs[poly] = utils`subjs[z][z^Range[0, Exponent[poly, z] - 1]];

(* Sliding windows of length `m` over a list. *)
cycles[m_Integer][x:(_List | _SparseArray)] := Range[0, m - 1] // RightComposition[
    Map[RotateLeft[x, #]&],
    Transpose,
    Part[#, ;; Length[x] - m + 1]&,
    Identity
];

(* Multiplication by powers of `z` modulo `poly` in the `j` basis. *)
cmats[poly_] := cmats[poly] = Module[{basis = stdjs[poly]},
    poly // RightComposition[
        Exponent[#, z]&,
        z^Range[0, 2 # - 2]&,
        Map[FQuolyMod[#, poly, z]&],
        utils`subjs[z],
        CoefficientArrays[#, basis]&,
        Last,
        cycles[Dimensions[#][[-1]]][#]&,
        Transpose[#, {1, 3, 2}]&,
        Identity
    ]
];

(* Differentiation with respect to `z` in the same `j` basis. *)
cmatdz[poly_] := cmatdz[poly] = Module[{basisPowers, basis},
    basisPowers = z^Range[0, Exponent[poly, z] - 1];
    basis = utils`subjs[z][basisPowers];
    basisPowers // RightComposition[
        D[#, z]&,
        utils`subjs[z],
        CoefficientArrays[#, basis]&,
        Last,
        If[Length[Dimensions[#]] < 2, SparseArray[{#}], #]&,
        Transpose,
        Identity
    ]
];


(* Matrix-valued differential forms.
 * `d` and `Wedge` currently come from `exterior.m`, which defines them
 * in `Global``.
 *)
ClearAll[dmat];
With[
    {
        dHead = Symbol["Global`d"],
        wedgeHead = Quiet[Symbol["Global`Wedge"], General::shdw]
    },
    dmat[xs_Plus, mat_] := xs // Map[dmat[#, mat]&];
    dmat[Times[c_, x:(_dHead | _wedgeHead)], mat_] /; FreeQ[c, _dHead | _wedgeHead] := dmat[x, c mat];
    HoldPattern[dmat[x_, mat1_] + dmat[x_, mat2_]] /; SameQ[Dimensions[mat1], Dimensions[mat2]] ^:= dmat[x, mat1 + mat2];
    HoldPattern[Times[c_, dmat[x_, mat_]]] /; FreeQ[c, _dHead | _wedgeHead] ^:= dmat[x, c mat];
    wedgeHead[dmat[x_, mat_]] ^:= dmat[wedgeHead[x], mat];
    wedgeHead[dmat[x1_, mat1_], dmat[x2_, mat2_]] /;
        SameQ[Dimensions[mat1][[-1]], Dimensions[mat2][[1]]] ^:= dmat[wedgeHead[x1, x2], Dot[mat1, mat2]];
    dmat[0, ___] := 0;
    dmat[_, mat_] /; ContainsOnly[Flatten[mat], {0}] := 0;
    dmat[x_Times, mat_] := dmat[Expand[x], mat];
];
Format[HoldPattern[dmat[x_, mat_]]] := x MatrixForm[mat];


SetAttributes[
    {
        stds,
        cmat,
        cmats,
        cmatdz,
        dmat
    },
    ReadProtected
];

End[]

EndPackage[]
